#!/bin/sh
set -e

export LC_COLLATE=C

TOP=$(pwd)
PANDOC=${PANDOC:-pandoc}
STYLESHEET=web_style.css

check_for_pandoc () {
    if ! which "$PANDOC" >/dev/null 2>&1
    then
        # Make things a little easier on SF.net servers.
        export PATH="$PATH:/home/groups/a/al/alleg/pandoc/bin"
        if ! which "$PANDOC" >/dev/null 2>&1
        then
            echo "$PANDOC not found in PATH"
            exit 1
        fi
    fi
}

page_files () {
    revdatesort $1/*
    echo INC.links
}

# Reverse any series of filenames containing dates.
revdatesort () {(
    acc=
    for x in "$@"
    do
        case "$x" in
            *[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*)
                acc="$x $acc"
                ;;
            *)
                echo "$acc"
                acc=
                echo "$x"
                ;;
        esac
    done
    echo "$acc"
)}

get_title () {
    grep -e "^$1=" "$TOP/en/META.title" | cut -d '=' -f 2-
}

# main
#-------

if test $# -ne 2
then
    echo "usage: $0 <input file> <output directory>"
    exit 1
fi

check_for_pandoc

indir="$( dirname $1 )"
inpage="$( basename $1 )"
case "$2" in
    /*) outdir="$2" ;;
    *)  outdir="$PWD/$2" ;;
esac
outpage="${outdir}/${inpage}.html"

# Sanity check that don't overwrite an input file by passing wrong args.
case "$outpage" in
    */OUT/*)
        ;;
    *)
        echo "Refusing to write to ${outpage}."
        exit 2
        ;;
esac

test -d "$outdir" || mkdir "$outdir"

cd "$indir"

page_files=$( page_files "$inpage" )
title="$( get_title $inpage )"

"$PANDOC" $page_files                           \
    --include-in-header INC.head                \
    --include-before-body INC.bodystart.html    \
    --include-after-body INC.bodyend.html       \
    --title-prefix "$title"                     \
    --css "$STYLESHEET"                         \
    --standalone                                \
    --output "$outpage"

# vim: ft=sh sts=4 sw=4 et:
