#!/bin/sh
# Barebones Atom feed generator for news items.
# Extracts the first line beginning with hashes as the entry title.

set -e

METAFILE="en/_meta/atom"
HOMEPAGE="https://liballeg.github.io/"

rfc3339_date () {
	# Validators say that T must be used as date-time separator.
	date --rfc-3339=seconds "$@" | tr ' ' 'T'
}

# Reverse any series of filenames containing dates.
revdatesort () {(
    acc=
    for x in "$@"
    do
        case "$x" in
            *[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*)
                acc="$x $acc"
                ;;
            *)
                echo "$acc"
                acc=
                echo "$x"
                ;;
        esac
    done
    echo "$acc"
)}

emit_top () {
	date=$1
	cat <<- EOF
	<?xml version="1.0" encoding="utf-8"?>
	<feed xmlns="http://www.w3.org/2005/Atom">
		<title>Allegro news</title>
		<link href="$HOMEPAGE"/>
		<link rel="self" href="${HOMEPAGE}feed_atom.xml"/>
		<updated>$date</updated>
		<id>urn:uuid:661257c2-82a0-4510-b2be-0f6b010807b9</id>
	EOF
}

emit_entry () {(
	file=$1
	uuid=$( grep "^$file uuid=" $METAFILE | cut -d= -f2- )
	date=$( grep "^$file date=" $METAFILE | cut -d= -f2- )

	if test -z "$uuid"
	then
		uuid="$( uuidgen )"
		date=$( rfc3339_date -r $file )
		echo "$file uuid=$uuid" >> $METAFILE
		echo "$file date=$date" >> $METAFILE
	fi

	title=$( grep '^#\+ ' $file | head -n 1 )
	title=${title#* }		# remove leading whitespace
	title=${title#????-??-?? - }	# remove leading date

	cat <<- EOF
	<entry>
		<title>$title</title>
		<author><name>Allegro developers</name></author>
		<link href="$HOMEPAGE"/>
		<id>urn:uuid:$uuid</id>
		<updated>$date</updated>
	</entry>
	EOF
)}

emit_bottom () {
	cat <<- EOF
	</feed>
	EOF
}

all_files=$( revdatesort "$@" )
first_date=$( rfc3339_date -r ${all_files%% *} )

>> $METAFILE

emit_top $first_date
for file in ${all_files}
do
	emit_entry $file
done
emit_bottom

# The <<- syntax strips tabs, so use tabs instead of spaces.
# vim: set ts=8 sts=8 sw=8 noet:
