#!/bin/sh
set -e

if test $# != 2
then
    echo "usage: $0 src dest"
    exit 1
fi

if ! which lndir >/dev/null 2>&1
then
    echo "lndir not found in PATH"
    exit 1
fi

mkdir -p $2
exec lndir ../$1 $2
